
export const newsData = [
    {
        id: 1,
        title:"Interview : Elton Zackhéous s'est confié au journal sportif Leaguepaper !",
        description:"Meilleur buteur du FC OSA, Elvis Zouhoulé a accordé une interview au média sportif ivoirien, Lekpakpato Sportif. Dans cette interview, il a évoqué ses débuts avec le FC OSA, son évolution, le soutien du président Amza Gamal et sa période difficile d'indisponibilité. Une interview exclusive à suivre !",
        image_principal: "/Assets/images/all-img/news4.jpg",
        image: "/Assets/images/all-img/news4.jpg",
        date: "11 FEB 2025",
        views: "1.2k",
        comments: "45",
        featured: true,
        type: "interview",
    },
    {
        id: 2,
        title: "J26-LIGUE 1 FC OSA/KORHOGO Le match du match",
        description:"",
        image_principal: "/Assets/images/all-img/news4.jpg",
        image: "https://youtu.be/pYg7Yd-ZhuI?si=x6mUbyqhbF6MzHHw",
        date: "10 FEB 2025",
        views: "890",
        comments: "23",
        featured: false,
        type: "video",
        hasVideo: true,
    },
    {
        id: 3,
        title: "Interview : Elvis au média sportif",
        description:"",
        image_principal: "/Assets/images/all-img/news4.jpg",
        image: "/Assets/images/all-img/news4.jpg",
        date: "11/05/2025",
        views: 63,
        comments: 0,
        featured: true,
        type: "interview",
    },
    {
        id: 4,
        title: "Ligue 1 LONACI - Grâce à son match nul (1-1) face à Lys",
        description:"",
        image_principal: "/Assets/images/all-img/news1.jpg",
        image: "/Assets/images/all-img/news1.jpg",
        date: "11/05/2025",
        views: 63,
        comments: 0,
        featured: true,
        type: "match",
    },
    {
        id: 5,
        title: "Les images du match FC OSA 1-3 FC SAN PEDRO",
        description:"",
        image_principal: "/Assets/images/all-img/news2.jpg",
        image: "/Assets/images/all-img/news2.jpg",
        date: "11/05/2025",
        views: 63,
        comments: 0,
        featured: true,
        type: "gallery",
    },
    {
        id: 6,
        title: "Ligue 1 LONACI - Le FC OSA s'incline (1-3) face au FC SAN-PEDRO",
        description:"",
        image_principal: "/Assets/images/all-img/news3.jpg",
        image: "/Assets/images/all-img/news3.jpg",
        date: "11/05/2025",
        views: 63,
        comments: 0,
        featured: true,
        type: "match",
    },
    {
        id: 7,
        title: "J29-LIGUE 1| LYS/FC OSA: Le match du maintien (1-1)",
        description:"",
        image_principal: "/Assets/images/news/new7.jpg",
        image: "/Assets/images/news/new7.jpg",
        date: "11/05/2025",
        views: 63,
        comments: 0,
        featured: true,
        type: "match",
    },
    {
        id: 8,
        title: "Détection U10 pour le centre de formation",
        description:"",
        image_principal: "/Assets/images/news/new6.jpg",
        image: "/Assets/images/news/new6.jpg",
        date: "11/05/2025",
        views: 63,
        comments: 0,
        featured: true,
        type: "match",
    },
    {
        id: 9,
        title: "Puissance 9 pour Zouhoulé Elvis!",
        description:"",
        image_principal: "/Assets/images/news/new8.jpg",
        image: "/Assets/images/news/new8.jpg",
        date: "11/05/2025",
        views: 63,
        comments: 0,
        featured: true,
        type: "match",
    },
    {
        id: 10,
        title: "Le FC OSA 13e à 2 journées de la fin!",
        description:"",
        image_principal: "/Assets/images/news/new5.jpg",
        image: "/Assets/images/news/new5.jpg",
        date: "11/05/2025",
        views: 63,
        comments: 0,
        featured: true,
        type: "match",
    },
];

// Fonction utilitaire pour trouver un joueur par son nom
export const findNewsById = (id: string) => {
  return   newsData.find(news => news.id === parseInt(id));
};
